### ISSUE TITLE
Places where runtime bugs interfere with compiler or language evolution

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#251]
This is a collection of issues where limitations or bugs in the current runtime have been impediments to compiler or language evolution. This list will evolve over time as new cases are identified or fixed.
- [ ] dotnet/roslyn#10126 Loader bug incorrectly reports struct cycle for static field (https://github.com/dotnet/runtime/issues/5479)
- [ ] Loader bug incorrectly reports struct cycle for unused type parameter (https://github.com/dotnet/runtime/issues/6924)
- [ ] Loader bug incorrectly reports struct cycle for array of type parameter (https://github.com/dotnet/runtime/issues/12024)
- [ ] #3711 Delegate combine fails at runtime (https://github.com/dotnet/runtime/issues/4556)
- [x] #1029 Bug in Activator.CreateInstance prevents default struct ctors (https://github.com/dotnet/runtime/issues/6536)
- [ ] https://github.com/dotnet/runtime/issues/15553   No API to pass Type.Missing argument through reflection calls. Completely blocks some "dynamic" scenarios involving optional parameters when platform requires interpreting. (C# binder uses Type.Missing to designate omitted arguments and it is a problem that they do not survive calls via reflection)
- [x] https://github.com/dotnet/csharplang/issues/124 Support generic attributes (https://github.com/dotnet/coreclr/pull/9189 runtime throws an exception when reflecting on an attribute type that is generic)
- [x] https://github.com/dotnet/runtime/issues/16402 https://github.com/dotnet/runtime/issues/24136 Reference assemblies are incorrect (omit needed private fields of structs)
