### ISSUE TITLE
[Umbrella] open issues in default interface method proposal

### ISSUE THREAD

**Issue by gafter** [dotnet/csharplang#285]
The following should be clarified/described in the [default interface implementation proposal](https://github.com/dotnet/csharplang/issues/52):

- [x] The spec should allow the modifier `public` to be used in an interface to make the default access explicit.
- [ ] The spec should describe the runtime method resolution algorithm in the face of interface default methods.
- [ ] Should (explicitly implemented) event accessors be permitted in an interface?
- [ ] Should `internal` members be permitted in an interface? If so, can they be non-virtual?
- [ ] Should `protected` members be permitted in an interface? If so, what, precisely, would that mean? Can they be abstract? Non-virtual?
- [ ] Which interfaces are searched (below)
- [ ] Diamond Inheritance between Class and Interface (below)

### Open Question: Which interfaces are searched

There is an open question which interfaces are searched for implementations, and in which order. For example, if we have

``` c#
interface IA { void M() {} }
interface IB: IA { override void M() {} }

class Base : IB { }
class Derived : Base, IA { }
```

Then is the override appearing in `IB` the final override selected for class `Derived`, even though `IB` does not appear in the interface list for `Derived`?

### Open Question: Diamond Inheritance between Class and Interface

What should occur in cases involving diamond inheritance with classes and interfaces:

``` c#
interface IA { void M() {} }
interface IB: IA { override void M() {} }

class Base : IA { void IA.M() { } }
class Derived : Base, IB { }
```

In this case neither `Base` nor `IB` is a subtype of the other. Is class `Derived` legal? If so, what is its implementation of `IA.M`?

**Comment by gafter** [comment]
The draft spec suggests that the following should be legal (because every concrete class declaration contains a most specific implementation for every interface method):

``` c#
interface IA
{
    void M() {}
}
class Derived: IA
{
    private void M() { }
}
```

I asked @MadsTorgersen to check on what his LDM notes and memory say about this situation. Mads said that he does not recall it being discussed, and his LDM notes do not show it being discussed. However, he believes it should behave the same way that this behaves:

``` c#
interface IA
{
    void M();
}
class Base: IA
{
    void IA.M() { }
}
class Derived: Base, IA
{
    private void M() { }
}
```

I agree with that: in either case `Derived` has a most specific implementation of `IA.M`, and so `IA` is fully implemented by `Derived`. The method `Derived.M` is simply not a candidate to implement `IA.M` and is unrelated to it. This agrees with the draft specification.

This treatment is also desirable to minimize the break that could be introduced by adding a new default method to an existing interface.

**Comment by bbarry** [comment]
> What happens when a private method in a class has the same signature as an interface's default method? 

I think it is logical to permit. It could potentially be a breaking change though right? Roslyn emits code today to call an explicit implementation of `Dispose()`, ignoring access restrictions. If someone had:

```CS
public class A : IDisposable, I2 {
    void IDisposable.Dispose() {/*something important enough to exist here, but apparently not important enough to make public*/}
}
interface I2 {}
```

and they changed `I2` to:

```CS
interface I2 { void Dispose() => throw null; }
```

What would happen at `using (A a ...)` blocks (and does it matter if `A` is a `class` or `struct`)? 

Are there other places in C#/VB where this is done? Does it matter if it becomes a breaking change to reflection or AOP practices ignoring said access keywords?

-----

Thought process...

What happens if signatures match on two different interfaces?

### Given:

```CS
class A : I1, I2 {
   private string PrivateM() => "A";
   protected string ProtectedM() => "A";
   public string PublicM() => "A";
   class B {}
}
class C : A {
   class D {}
}
interface I1 {}
interface I2 {}
```

### Changes made...

assume `instance is A a && ...` for each testcase

#### scenario 1:

```CS
interface I1 { string M(); }
```

The proposal would only impact scenarios where the interface provides an implementation right? So this would be the same as it is today:

Compile error in class `A`.  `TypeLoadException` if `A` is in a different assembly that is not recompiled but is instantiated.

* if `M` were instead `PrivateM`  the result would be the same.
* if `M` were instead `PublicM`, `a.PublicM() == "A"` regardless of build of assembly containing `A` or location of call (no change to current method resolution here) Should `((I1)a).ProtectedM() == "I1"`?

#### scenario 2:

```CS
interface I1 { string M() => "I1"; }
```

Ok? (the goal of the proposal is to make extending the interface in this way not a breaking change right?) `a.M() == "I1"`

* if `M` were instead `PrivateM`:
  * externally `a.PrivateM() == "I1"`
  * code internal to `A` or `B`: `a.PrivateM() == "A"` (should `((I1)a).PrivateM() == "I1"`?)
  * code internal to `C` or `D`: `a.PrivateM() == "I1"`
* if `M` were instead `ProtectedM`:
  * externally `a.ProtectedM() == "I1"`,
  * code internal to `A` or `B` or `C`: `a.ProtectedM() == "A"` (should `((I1)a).ProtectedM() == "I1"`?)
  * code internal to `D`: `a.ProtectedM() == "I1"`
* if `M` were instead `PublicM`, interface implementation is ignored proceed as if scenario 1 (everything works, no change to current method resolution here)

#### scenario 3:

```CS
interface I1 { void M() => Console.WriteLine("I1"); }
interface I2 { void M(); }
```

Still ok? Even if all 3 types are in different assemblies and `A` is not rebuilt? And build order between `I1` and `I2` doesn't matter. Effectively same as scenario 2?

This would mean scenario 1 could be fixed by rebuilding assembly containing `I2` with a method implementation instead of being forced to rebuild assembly containing `A` with an implementation. That seems kinda weird but ok I guess.

#### scenario 4:

```CS
interface I1 { void M() => Console.WriteLine("I1"); }
interface I2 { void M() => Console.WriteLine("I2"); }
```

Compile error in class `A`?  `TypeLoadException` if `A` is in a different assembly that is not recompiled but is instantiated?

**Comment by bbarry** [comment]
edit: removed my comment (will remove this one in case you noticed in a few minutes). Mads thoughts seem right to me (post appeared right before I submit).

**Comment by gafter** [comment]
I have added two open questions to this issue.

**Comment by bbarry** [comment]
```CS
interface IA { int M() => 1; }
interface IB: IA { override int M() => 2; }
class Base : IB { }
class Derived : Base, IA { }
```

should behave like this:

```CS
interface IA { int M() }
interface IB: IA { int M(); }

class Base: IB
{
    public virtual int M() => 2;
}
class Derived: Base, IA
{
}
```

under a rule that `class` inheritance takes precedence over interface inheritance and that once a class implements an interface, all interface implementations would resolve as if they are class implementations from the perspective of inheriting classes.

The difference between these two samples would be that that instance methods inside both classes and the IB interface could refer to `base.IA.M()` or some similar syntax to call that specific implementation. The former for example could become: 

```CS
interface IA { int M() => 1; }
interface IB: IA { override int M() => 2; }
class Base : IB { }
class Derived : Base, IA { 
    public override int M() => base.IA.M();
}
```

**Comment by gafter** [comment]
@bbarry The spec has been modified to give classes priority over interfaces. Moreover, the *most specific override* rule (also added to the spec) now answers this question the same way.

All of the issues here have been answered or moved to another issue, so I'm closing this. See https://github.com/dotnet/csharplang/issues/406 for issues to be taken up by the LDM.
